# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

services:
  - docker
language: generic

notifications:
  email:
    on_success: always
    on_failure: always

env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=xenial
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=bionic
    - ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=debian OS_CODE_NAME=stretch
    - ROS_DISTRO=noetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=ubuntu OS_CODE_NAME=focal

matrix:
  include:
    - name: "Run flake8 tests on Python 2.7"
      language: python
      python: "2.7"
      install: pip install flake8
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude '*/rosbridge_library/util/cbor.py'
    - name: "Run flake8 tests on Python 3.8"
      language: python
      python: "3.8"
      dist: focal
      install: pip install flake8
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude '*/rosbridge_library/util/cbor.py'
  allow_failures:
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian OS_NAME=debian OS_CODE_NAME=stretch

branches:
  only:
    - master
    - develop

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - source .industrial_ci/travis.sh
